package com.sistcontable.model;
// Generated 06-07-2015 01:25:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private BigDecimal idBitacora;
     private Usuario usuario;
     private Date fechaIngreso;

    public Bitacora() {
    }

	
    public Bitacora(BigDecimal idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Bitacora(BigDecimal idBitacora, Usuario usuario, Date fechaIngreso) {
       this.idBitacora = idBitacora;
       this.usuario = usuario;
       this.fechaIngreso = fechaIngreso;
    }
   
    public BigDecimal getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(BigDecimal idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


