package com.sistcontable.model;
// Generated 06-10-2015 01:21:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private BigDecimal idCuenta;
     private Estado estado;
     private Rubro rubro;
     private String nombreCuenta;
     private BigDecimal cuentaMayor;
     private Set transaccions = new HashSet(0);
     private Set movimientos = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(BigDecimal idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Cuenta(BigDecimal idCuenta, Estado estado, Rubro rubro, String nombreCuenta, BigDecimal cuentaMayor, Set transaccions, Set movimientos) {
       this.idCuenta = idCuenta;
       this.estado = estado;
       this.rubro = rubro;
       this.nombreCuenta = nombreCuenta;
       this.cuentaMayor = cuentaMayor;
       this.transaccions = transaccions;
       this.movimientos = movimientos;
    }
   
    public BigDecimal getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(BigDecimal idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    public String getNombreCuenta() {
        return this.nombreCuenta;
    }
    
    public void setNombreCuenta(String nombreCuenta) {
        this.nombreCuenta = nombreCuenta;
    }
    public BigDecimal getCuentaMayor() {
        return this.cuentaMayor;
    }
    
    public void setCuentaMayor(BigDecimal cuentaMayor) {
        this.cuentaMayor = cuentaMayor;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


