package com.sistcontable.model;
// Generated 06-07-2015 01:25:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private BigDecimal idDepartamento;
     private String nombreDepto;
     private Set municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(BigDecimal idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(BigDecimal idDepartamento, String nombreDepto, Set municipios) {
       this.idDepartamento = idDepartamento;
       this.nombreDepto = nombreDepto;
       this.municipios = municipios;
    }
   
    public BigDecimal getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(BigDecimal idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDepto() {
        return this.nombreDepto;
    }
    
    public void setNombreDepto(String nombreDepto) {
        this.nombreDepto = nombreDepto;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


