package com.sistcontable.model;
// Generated 06-10-2015 01:21:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleEstado generated by hbm2java
 */
public class DetalleEstado  implements java.io.Serializable {


     private BigDecimal idDetalleEstado;
     private Estado estado;
     private Date fechaInicio;
     private Date fechaFin;
     private BigDecimal saldoTotal;
     private String rutaDocumento;

    public DetalleEstado() {
    }

	
    public DetalleEstado(BigDecimal idDetalleEstado) {
        this.idDetalleEstado = idDetalleEstado;
    }
    public DetalleEstado(BigDecimal idDetalleEstado, Estado estado, Date fechaInicio, Date fechaFin, BigDecimal saldoTotal, String rutaDocumento) {
       this.idDetalleEstado = idDetalleEstado;
       this.estado = estado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.saldoTotal = saldoTotal;
       this.rutaDocumento = rutaDocumento;
    }
   
    public BigDecimal getIdDetalleEstado() {
        return this.idDetalleEstado;
    }
    
    public void setIdDetalleEstado(BigDecimal idDetalleEstado) {
        this.idDetalleEstado = idDetalleEstado;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public BigDecimal getSaldoTotal() {
        return this.saldoTotal;
    }
    
    public void setSaldoTotal(BigDecimal saldoTotal) {
        this.saldoTotal = saldoTotal;
    }
    public String getRutaDocumento() {
        return this.rutaDocumento;
    }
    
    public void setRutaDocumento(String rutaDocumento) {
        this.rutaDocumento = rutaDocumento;
    }




}


