package com.sistcontable.model;
// Generated 06-07-2015 01:25:15 PM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String enombre;
     private String edireccion;
     private Integer telefono;

    public Empresa() {
    }

	
    public Empresa(String enombre) {
        this.enombre = enombre;
    }
    public Empresa(String enombre, String edireccion, Integer telefono) {
       this.enombre = enombre;
       this.edireccion = edireccion;
       this.telefono = telefono;
    }
   
    public String getEnombre() {
        return this.enombre;
    }
    
    public void setEnombre(String enombre) {
        this.enombre = enombre;
    }
    public String getEdireccion() {
        return this.edireccion;
    }
    
    public void setEdireccion(String edireccion) {
        this.edireccion = edireccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }




}


