package com.sistcontable.model;
// Generated 06-07-2015 11:50:17 AM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String enombre;
     private String edireccion;
     private Integer telefono;
     private String propietario;
     private String contador;

    public Empresa() {
    }

	
    public Empresa(String enombre) {
        this.enombre = enombre;
    }
    public Empresa(String enombre, String edireccion, Integer telefono, String propietario, String contador) {
       this.enombre = enombre;
       this.edireccion = edireccion;
       this.telefono = telefono;
       this.propietario = propietario;
       this.contador = contador;
    }
   
    public String getEnombre() {
        return this.enombre;
    }
    
    public void setEnombre(String enombre) {
        this.enombre = enombre;
    }
    public String getEdireccion() {
        return this.edireccion;
    }
    
    public void setEdireccion(String edireccion) {
        this.edireccion = edireccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(String propietario) {
        this.propietario = propietario;
    }
    public String getContador() {
        return this.contador;
    }
    
    public void setContador(String contador) {
        this.contador = contador;
    }




}


