package com.sistcontable.model;
// Generated 06-10-2015 01:21:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String enombre;
     private BigDecimal idEmpresa;
     private String edireccion;
     private Integer telefono;

    public Empresa() {
    }

	
    public Empresa(String enombre, BigDecimal idEmpresa) {
        this.enombre = enombre;
        this.idEmpresa = idEmpresa;
    }
    public Empresa(String enombre, BigDecimal idEmpresa, String edireccion, Integer telefono) {
       this.enombre = enombre;
       this.idEmpresa = idEmpresa;
       this.edireccion = edireccion;
       this.telefono = telefono;
    }
   
    public String getEnombre() {
        return this.enombre;
    }
    
    public void setEnombre(String enombre) {
        this.enombre = enombre;
    }
    public BigDecimal getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(BigDecimal idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getEdireccion() {
        return this.edireccion;
    }
    
    public void setEdireccion(String edireccion) {
        this.edireccion = edireccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }




}


