package com.sistcontable.model;
// Generated 06-10-2015 01:21:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private BigDecimal idEstado;
     private String nombreEstado;
     private BigDecimal disponibilidad;
     private Set detalleEstados = new HashSet(0);
     private Set cuentas = new HashSet(0);

    public Estado() {
    }

	
    public Estado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }
    public Estado(BigDecimal idEstado, String nombreEstado, BigDecimal disponibilidad, Set detalleEstados, Set cuentas) {
       this.idEstado = idEstado;
       this.nombreEstado = nombreEstado;
       this.disponibilidad = disponibilidad;
       this.detalleEstados = detalleEstados;
       this.cuentas = cuentas;
    }
   
    public BigDecimal getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    public BigDecimal getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(BigDecimal disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public Set getDetalleEstados() {
        return this.detalleEstados;
    }
    
    public void setDetalleEstados(Set detalleEstados) {
        this.detalleEstados = detalleEstados;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


