package com.sistcontable.model;
// Generated 06-10-2015 01:21:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private BigDecimal idMunic;
     private Departamento departamento;
     private String nombreMunic;
     private Set personas = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(BigDecimal idMunic) {
        this.idMunic = idMunic;
    }
    public Municipio(BigDecimal idMunic, Departamento departamento, String nombreMunic, Set personas) {
       this.idMunic = idMunic;
       this.departamento = departamento;
       this.nombreMunic = nombreMunic;
       this.personas = personas;
    }
   
    public BigDecimal getIdMunic() {
        return this.idMunic;
    }
    
    public void setIdMunic(BigDecimal idMunic) {
        this.idMunic = idMunic;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreMunic() {
        return this.nombreMunic;
    }
    
    public void setNombreMunic(String nombreMunic) {
        this.nombreMunic = nombreMunic;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


