package com.sistcontable.model;
// Generated 06-07-2015 01:25:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private BigDecimal idPersona;
     private Municipio municipio;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String cargo;
     private String sexo;
     private Date fechaNac;
     private String dui;
     private String EMail;
     private String direccion;
     private Set telefonos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Persona() {
    }

	
    public Persona(BigDecimal idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(BigDecimal idPersona, Municipio municipio, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String cargo, String sexo, Date fechaNac, String dui, String EMail, String direccion, Set telefonos, Set usuarios) {
       this.idPersona = idPersona;
       this.municipio = municipio;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.cargo = cargo;
       this.sexo = sexo;
       this.fechaNac = fechaNac;
       this.dui = dui;
       this.EMail = EMail;
       this.direccion = direccion;
       this.telefonos = telefonos;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(BigDecimal idPersona) {
        this.idPersona = idPersona;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return primerNombre+" "+primerApellido;
    }
    
    

}


