package com.sistcontable.model;
// Generated 06-07-2015 01:25:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Privilegio generated by hbm2java
 */
public class Privilegio  implements java.io.Serializable {


     private BigDecimal idPrivilegio;
     private String nombrePrivilegio;
     private String descripcion;
     private Set usuarios = new HashSet(0);

    public Privilegio() {
    }

	
    public Privilegio(BigDecimal idPrivilegio) {
        this.idPrivilegio = idPrivilegio;
    }
    public Privilegio(BigDecimal idPrivilegio, String nombrePrivilegio, String descripcion, Set usuarios) {
       this.idPrivilegio = idPrivilegio;
       this.nombrePrivilegio = nombrePrivilegio;
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getIdPrivilegio() {
        return this.idPrivilegio;
    }
    
    public void setIdPrivilegio(BigDecimal idPrivilegio) {
        this.idPrivilegio = idPrivilegio;
    }
    public String getNombrePrivilegio() {
        return this.nombrePrivilegio;
    }
    
    public void setNombrePrivilegio(String nombrePrivilegio) {
        this.nombrePrivilegio = nombrePrivilegio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


