package com.sistcontable.model;
// Generated 06-07-2015 01:25:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rubro generated by hbm2java
 */
public class Rubro  implements java.io.Serializable {


     private BigDecimal idRubro;
     private String nombreRubro;
     private String tipoRubro;
     private Set cuentas = new HashSet(0);

    public Rubro() {
    }

	
    public Rubro(BigDecimal idRubro) {
        this.idRubro = idRubro;
    }
    public Rubro(BigDecimal idRubro, String nombreRubro, String tipoRubro, Set cuentas) {
       this.idRubro = idRubro;
       this.nombreRubro = nombreRubro;
       this.tipoRubro = tipoRubro;
       this.cuentas = cuentas;
    }
   
    public BigDecimal getIdRubro() {
        return this.idRubro;
    }
    
    public void setIdRubro(BigDecimal idRubro) {
        this.idRubro = idRubro;
    }
    public String getNombreRubro() {
        return this.nombreRubro;
    }
    
    public void setNombreRubro(String nombreRubro) {
        this.nombreRubro = nombreRubro;
    }
    public String getTipoRubro() {
        return this.tipoRubro;
    }
    
    public void setTipoRubro(String tipoRubro) {
        this.tipoRubro = tipoRubro;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


