package com.sistcontable.model;
// Generated 06-07-2015 11:50:17 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private Persona persona;
     private Privilegio privilegio;
     private String nombreUsuario;
     private String clave;
     private Set transaccions = new HashSet(0);
     private Set bitacoras = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(BigDecimal idUsuario, Persona persona, Privilegio privilegio, String nombreUsuario, String clave, Set transaccions, Set bitacoras) {
       this.idUsuario = idUsuario;
       this.persona = persona;
       this.privilegio = privilegio;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
       this.transaccions = transaccions;
       this.bitacoras = bitacoras;
    }
   
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Privilegio getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(Privilegio privilegio) {
        this.privilegio = privilegio;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }




}


