package com.sistcontable.model;
// Generated 05-16-2015 05:08:50 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;




/**
 * Persona generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

     private double id_usuario;
     private Double id_privilegio;
     private double id_persona;
     private String nombre_usuario;
     private String clave;

     
    public Usuario() {
        
    } 
     
    public Usuario(double id_usuario, double id_persona, String nombre_usuario, String clave) {
        this.id_usuario = id_usuario;
        this.id_persona = id_persona;
        this.nombre_usuario = nombre_usuario;
        this.clave = clave;
    }

    public double getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(double id_usuario) {
        this.id_usuario = id_usuario;
    }

    public Double getId_privilegio() {
        return id_privilegio;
    }

    public void setId_privilegio(Double id_privilegio) {
        this.id_privilegio = id_privilegio;
    }

    public double getId_persona() {
        return id_persona;
    }

    public void setId_persona(double id_persona) {
        this.id_persona = id_persona;
    }

    public String getNombre_usuario() {
        return nombre_usuario;
    }

    public void setNombre_usuario(String nombre_usuario) {
        this.nombre_usuario = nombre_usuario;
    }

    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

     
   

    @Override
    public String toString() {
        return nombre_usuario;
    }
}


