/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistcontable.formularios;

import com.sistcontable.dao.PersonaDAO;
import com.sistcontable.dao.UsuarioDAO;
import com.sistcontable.model.Persona;
import com.sistcontable.model.Usuario;
import java.net.URL;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Manuel Miranda
 */
public class FrmUsuario extends javax.swing.JPanel {
     Usuario usuario = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    private DefaultListModel modeloLista = new DefaultListModel();
    private List<Usuario> objUsuario;
    private String idActual;
    private Boolean isUpdate = Boolean.FALSE;

    /**
     * Creates new form FrmTab1
     */
    public FrmUsuario() {
        initComponents();
        Actualizar_lista();
        jList1.setModel(modeloLista);
        textID.setEditable(false);
        textNombre.setEditable(false);
        textPersona.setEditable(false);
        textClave.setEditable(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelInformacion = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textPersona = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textClave = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1059, 515));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/editar.png"))); // NOI18N
        jButton1.setToolTipText("Editar");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/editnew.png"))); // NOI18N
        jButton2.setToolTipText("Nuevo");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/filesave.png"))); // NOI18N
        jButton3.setToolTipText("Guardar");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/delete.png"))); // NOI18N
        jButton4.setToolTipText("Eliminar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personas"));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de persona"));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/editnew.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/filesave.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID_usuario");

        jLabel2.setText("Id_persona");

        jLabel3.setText("Nombre_usuario");

        jLabel4.setText("Clave");

        labelInformacion.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        labelInformacion.setForeground(new java.awt.Color(255, 0, 0));
        labelInformacion.setText("jLabel5");

        textClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textNombre)
                                    .addComponent(textClave)
                                    .addComponent(textID)
                                    .addComponent(textPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(textClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(694, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
         labelMensaje.setText("");
        labelMensaje.setIcon(null);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
       int index = jList1.getSelectedIndex();
        if (index != -1) {
            Usuario objMostrarUsuario = (Usuario) modeloLista.getElementAt(index);
            idActual = String.valueOf(objMostrarUsuario.getId_usuario());            
            textID.setText(idActual);
            textNombre.setText(objMostrarUsuario.getNombre_usuario());
            textPersona.setText(String.valueOf(objMostrarUsuario.getId_persona()));
            textClave.setText(objMostrarUsuario.getClave());     
            labelInformacion.setText(objMostrarUsuario.getNombre_usuario());
        }
        textID.setEditable(false);
        textNombre.setEditable(false);
        textPersona.setEditable(false);
        textClave.setEditable(false);
        //labelMensaje.setText("");
        //labelMensaje.setIcon(null);
    }//GEN-LAST:event_jList1ValueChanged

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        isUpdate = Boolean.TRUE;
        
        labelMensaje.setText("");
        labelMensaje.setIcon(null);
        textNombre.setEditable(true);
        textID.setEditable(true);
        textClave.setEditable(true);
        textPersona.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
      isUpdate = Boolean.FALSE;
        
        labelMensaje.setText("");
        labelMensaje.setIcon(null);
        textID.setEditable(true);
        textNombre.setEditable(true);
        textPersona.setEditable(true);
        textClave.setEditable(true);
        
        textID.setText("");
        textNombre.setText("");
        textPersona.setText("");
        textClave.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       boolean resp = Boolean.FALSE;
        if(textID.getText().equals("") || textNombre.getText().equals("") || textPersona.getText().equals("")
                || textClave.getText().equals("")){
            MostrarMensaje("Uno o mas campos estan vacios","cancel.png", labelMensaje);
        }else{
            usuario.setId_usuario(Double.parseDouble(textID.getText()));
            usuario.setNombre_usuario(textNombre.getText());
            usuario.setId_persona(Double.parseDouble(textPersona.getText()));
            usuario.setClave(textClave.getText());
            
            if(isUpdate)
                resp=usuarioDAO.updateUser(usuario);
            else
                resp=usuarioDAO.saveUser(usuario);

            if (resp) {
                MostrarMensaje("Usuario Registrado Corecctamente","ok.png", labelMensaje);
                Actualizar_lista();
            } else {
                MostrarMensaje("Error al tratar de Registrar el Usuario","cancel.png", labelMensaje);
            }
            
        }         
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         boolean resp = Boolean.FALSE;
        resp=usuarioDAO.deleteUser(idActual);        
        Actualizar_lista();        
        if(resp)
            MostrarMensaje("Registro Eliminado","ok.png", labelMensaje);
        else
            MostrarMensaje("Error al tratar de eliminar el registro","cancel.png", labelMensaje);
       
    }//GEN-LAST:event_btnEliminarActionPerformed

      public void Actualizar_lista() {
        objUsuario = usuarioDAO.searchAllUser();
        if (!(objUsuario.isEmpty())) {
            this.modeloLista.clear();
            for (int i = 0; i < objUsuario.size(); i++) {
                modeloLista.addElement(objUsuario.get(i));
            }
            jList1.setSelectedIndex(0);
        }      
    }
    
    public void MostrarMensaje(String msj, String nameImagen, JLabel label) {
        label.setText(msj);
        String path = "/com/sistcontable/imagenes/"+nameImagen;
        URL url = this.getClass().getResource(path); 
        ImageIcon icon = new ImageIcon(url);
        label.setIcon(icon);
    }
    
    private void textClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JTextField textClave;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPersona;
    // End of variables declaration//GEN-END:variables
}
