/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistcontable.formularios;

import com.sistcontable.dao.PersonaDAO;
import com.sistcontable.dao.UsuarioDAO;
import com.sistcontable.model.Persona;
import com.sistcontable.model.Usuario;
import java.net.URL;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Miranda
 */
public class FrmUsuario extends javax.swing.JPanel {
    Usuario usuario = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    private DefaultListModel modeloLista = new DefaultListModel();
    private List<Usuario> objUsuario;
    private String idActual;
    private Boolean isUpdate = Boolean.FALSE;

    /**
     * Creates new form FrmTab1
     */
    public FrmUsuario() {
        initComponents();
        Actualizar_lista();
        jList1.setModel(modeloLista);
        textID.setEditable(false);
        textNombre.setEditable(false);
        listaIdPersona.setEditable(false);
        textClave.setEditable(false);
        List<Persona> lista =new ArrayList();
        Persona[] personas;
        personas=usuarioDAO.listaPersonas(); 
        int longPersonas=personas.length;
        String[] listaP=new String[longPersonas];
        for(int i=0;i<longPersonas;i++){
            listaP[i]=personas[i].getIdPersona().intValue()+" "+personas[i].getPrimerNombre()+" "+personas[i].getPrimerApellido();
        }
        listaIdPersona.setModel(new DefaultComboBoxModel(listaP));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelInformacion = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textClave = new javax.swing.JTextField();
        listaIdPersona = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(1059, 515));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personas"));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de persona"));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/editnew.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/filesave.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sistcontable/imagenes/delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID de usuario");

        jLabel2.setText("Id de persona");

        jLabel3.setText("Nombre de usuario");

        jLabel4.setText("Clave");

        labelInformacion.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        labelInformacion.setForeground(new java.awt.Color(255, 0, 0));
        labelInformacion.setText("Gestión de usuarios");

        textClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btnEditar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listaIdPersona, 0, 214, Short.MAX_VALUE)
                                    .addComponent(textNombre)
                                    .addComponent(textClave)
                                    .addComponent(textID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 145, Short.MAX_VALUE)))))
                .addGap(103, 103, 103))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar)
                    .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(listaIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnNuevo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(7, 7, 7)))
                        .addComponent(textClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Gestion de usuario");
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
         labelMensaje.setText("");
        labelMensaje.setIcon(null);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
       int index = jList1.getSelectedIndex();
       int id=0,i=0;
        if (index != -1) {
            Usuario objMostrarUsuario = (Usuario) modeloLista.getElementAt(index);
            idActual = String.valueOf(objMostrarUsuario.getId_usuario());            
            textID.setText(idActual);
            textNombre.setText(objMostrarUsuario.getNombre_usuario());
         //   textPersona.setText(String.valueOf(objMostrarUsuario.getId_persona()));
            textClave.setText(objMostrarUsuario.getClave());     
            labelInformacion.setText(objMostrarUsuario.getNombre_usuario());
            for(i=0;i<listaIdPersona.getItemCount();i++){
                if(String.valueOf(objMostrarUsuario.getId_persona()).contains(obtenerNumero(listaIdPersona.getItemAt(i).toString()))){
                   System.out.println("num lista "+obtenerNumero(listaIdPersona.getItemAt(i).toString()));
                   System.out.println("num id "+String.valueOf(objMostrarUsuario.getId_persona()));
                   System.out.println("son iguales ---"+i);
                    id=i;} 
            }            
           // listaIdPersona.setSelectedItem(id);
           if(listaIdPersona.getItemCount()>1) 
            listaIdPersona.setSelectedIndex(id);
        }
        textID.setEditable(false);
        textNombre.setEditable(false);
      //  textPersona.setEditable(false);
        listaIdPersona.setEditable(false);
        textClave.setEditable(false);
        //labelMensaje.setText("");
        //labelMensaje.setIcon(null);
    }//GEN-LAST:event_jList1ValueChanged

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        isUpdate = Boolean.TRUE;        
        labelMensaje.setText("");
        labelMensaje.setIcon(null);
        textNombre.setEditable(true);
        textID.setEditable(true);
        textClave.setEditable(true);
     //   textPersona.setEditable(true);
        listaIdPersona.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
      isUpdate = Boolean.FALSE;
        
        labelMensaje.setText("");
        labelMensaje.setIcon(null);
        textID.setEditable(false);
        textNombre.setEditable(true);
        //textPersona.setEditable(true);
        listaIdPersona.setEditable(true);
        textClave.setEditable(true);
        
        textID.setText("");
        textNombre.setText("");
        //textPersona.setText("");
        textClave.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       boolean resp = Boolean.FALSE;
        if(textNombre.getText().equals("") || listaIdPersona.getSelectedItem().toString().equals("")
                || textClave.getText().equals("")){
            MostrarMensaje("Uno o mas campos estan vacios","cancel.png", labelMensaje);
        }else{
            if(isUpdate){
                usuario.setId_usuario(Double.parseDouble(textID.getText()));
                 usuario.setNombre_usuario(textNombre.getText());
                 usuario.setId_persona(Double.parseDouble(obtenerNumero(listaIdPersona.getSelectedItem().toString())));
                  usuario.setClave(textClave.getText());
                resp=usuarioDAO.updateUser(usuario);}
            else{
                    usuario.setNombre_usuario(textNombre.getText());
                 usuario.setId_persona(Double.parseDouble(obtenerNumero(listaIdPersona.getSelectedItem().toString())));
                  usuario.setClave(textClave.getText());
                resp=usuarioDAO.saveUser(usuario);}

            if (resp) {
                MostrarMensaje("Usuario Registrado Corecctamente","ok.png", labelMensaje);
                Actualizar_lista();
            } else {
                MostrarMensaje("Error al tratar de Registrar el Usuario","cancel.png", labelMensaje);
            }
            
        }         
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(textID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario para eliminar");
            return;
        }
        textID.setEditable(true);
        textNombre.setEditable(false);
        listaIdPersona.setEditable(false);
        textClave.setEditable(false);
         boolean resp = Boolean.FALSE;
        resp=usuarioDAO.deleteUser(idActual);        
        Actualizar_lista();        
        if(resp)
            MostrarMensaje("Registro Eliminado","ok.png", labelMensaje);
        else
            MostrarMensaje("Error al tratar de eliminar el registro","cancel.png", labelMensaje);
       
    }//GEN-LAST:event_btnEliminarActionPerformed

      public void Actualizar_lista() {
        objUsuario = usuarioDAO.searchAllUser();
        if (!(objUsuario.isEmpty())) {
            this.modeloLista.clear();
            for (int i = 0; i < objUsuario.size(); i++) {
                modeloLista.addElement(objUsuario.get(i));
            }
            jList1.setSelectedIndex(0);
        }      
    }
      
    public String obtenerNumero(String cadena){
        String numeros="",letras="";
        for (short indice = 0; indice < cadena.length(); indice++){
          char caracter = cadena.charAt(indice);
        if(esNumero(caracter)){
            numeros += caracter;
        }else{
        letras += caracter;
        }
        }
    return numeros;    
    }
    
    private static boolean esNumero(char caracter){
    try {
    Integer.parseInt(String.valueOf(caracter));
    return true;
    } catch (NumberFormatException ex){
    return false;
        }
        }
    
    public void MostrarMensaje(String msj, String nameImagen, JLabel label) {
        label.setText(msj);
        String path = "/com/sistcontable/imagenes/"+nameImagen;
        URL url = this.getClass().getResource(path); 
        ImageIcon icon = new ImageIcon(url);
        label.setIcon(icon);
    }
    
    private void textClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JComboBox listaIdPersona;
    private javax.swing.JTextField textClave;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
